[project]
name = "rag-system"
version = "0.1.0"
description = "Production Ready RAG"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "redis",
    "rq",
    "qdrant-client",
    "pydantic-settings",

    "langchain",
    "langchain-community",
    "langchain-qdrant",
    "langchain-huggingface",
    "langchain-text-splitters",

    "torch",
    "sentence-transformers",

    "pypdf",
    "python-multipart",

    "groq",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[tool.uv]